### ISSUE TITLE
Won't compile on 1.17.0-nightly due to missing type annotation

### ISSUE THREAD

**Issue by fkjogu** [a8m/pb#47]
The type cannot be automatically resolved.

```
error[E0283]: type annotations required: cannot resolve `std::string::String: std::convert::AsRef<_>`
   --> src/pb.rs:378:64
    |
378 |                         base = base + repeat!(self.bar_current.as_ref(), curr_count - 1) +
    |                                       -------------------------^^^^^^------------------- in this macro invocation
```
