### PR TITLE
Turn .as_ref() calls into .to_string() calls to remove type ambiguity.

### LINKED ISSUE #47: Won't compile on 1.17.0-nightly due to missing type annotation
The type cannot be automatically resolved.

```
error[E0283]: type annotations required: cannot resolve `std::string::String: std::convert::AsRef<_>`
   --> src/pb.rs:378:64
    |
378 |                         base = base + repeat!(self.bar_current.as_ref(), curr_count - 1) +
    |                                       -------------------------^^^^^^------------------- in this macro invocation
```

### PR DESCRIPTION
**Pull request by fkjogu**
Fixes #47 
I'm not sure, why you have put `.as_ref()` here in the first place. So maybe I'm missing something.

### CODE REVIEW

**Comment by a8m** [comment]
👍 
Thanks @fkjogu
