### ISSUE TITLE
Type annotations required for rustc 1.18.0-nightly

### ISSUE THREAD

**Issue by pornel** [a8m/pb#50]
The latest release doesn't build with rustc 1.18.0-nightly (50c186419 2017-04-06)

> error[E0283]: type annotations required: cannot resolve `std::string::String: std::convert::AsRef<_>`
   --> …/pbr-0.3.1/src/pb.rs:348:64
```
    |
348 |                         base = base + repeat!(self.bar_current.as_ref(), curr_count - 1) +
    |                                                                ^^^^^^
```

**Comment by a8m** [comment]
Hey @pornel,
Which version are you using? it fixed in pbr-1.0.0-alpha.3.

**Comment by pornel** [comment]
I only ran into this problem, because this crate is a dependency-of-a-dependency.

but crates.io still recommends 0.3:

https://crates.io/crates/pbr

**Comment by bluss** [comment]
pbr 0.3.1 issue appears in http://cargobomb-reports.s3-website-us-west-1.amazonaws.com/stable-v-beta-2017-04-10/index.html and affects at least one dependency (sonic 0.6)

**Comment by a8m** [comment]
I published a stable version. it should work fine now.

I'm closing this issue, but feel free to open it if you still have problems with that.
